### PR TITLE
[ENH] The part entity

### PR DESCRIPTION
**Pull request by agahkarakuzu**
This PR adds a description for the `part` entity that identifies whether reconstructed anatomical image contains [magnitude or phase](http://dicom.nema.org/medical/dicom/2017d/output/chtml/part03/sect_C.8.13.3.html) information.

### CODE REVIEW

**Comment by agahkarakuzu** [comment]
Should we consider `real` and `imag` here as well, or is it too much?

**Comment by Gilles86** [comment]
Not sure. 

Would be kind of nice and easy to integrate. 

Then again, from an information perspective, if you have `magnitude` and `phase`, you have `real` and `imag` (right?!). It will be less work for future workflow developers if they know which of these two formats (`real/imag` vs `phase/magnitude`) will be used in any BIDS-compatible input data.

So I think I would vote against it, but I'm open to be convinced.

**Comment by agahkarakuzu** [comment]
> Then again, from an information perspective, if you have magnitude and phase, you have real and imag (right?!)

To properly reconstruct phase images, one usually need images from multiple channels. I remember the disappointment when sqrt(Re <sup>2</sup> + Im<sup>2</sup>) gave me the same magnitude image scanner gave, but arctan<sup>-1</sup>(Im/Re) did not give the same phase image :) Phase measured in each channel is subjected to that channel's sensitivity profile, so it is required to combine them to get proper phase images. Bottomline, without that information `real/imag` --> `mag/phase` transformation is not that ideal and vice versa. 

I know that methods like `fslcomplex` has more through implementations for mag/phase conversion as a prior step for B0 estimation, for which the above non-ideal situation would not be a concern. But allowing `part` to use `real`, `imag` would be good for allowing some other qMRI applications, such as QSM.

**Comment by Gilles86** [comment]
Ah, good to have a proper MR physicist on board, @Agah 😆.

So I'm all for `real/imag` as well then. Can you draft something up?

I also slightly edited this text because I think it still needed to be converted from the old repo. See https://github.com/bids-bep001/bids-specification/pull/18

**Comment by ChristophePhillips** [comment]
Yes the `real`/`imag` seems a good idea and also a simple back-compatible extension

**Pull request merged**
